version: '3.8'

services:
  # NestJS API Gateway
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: powerflow-api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
    networks:
      - powerflow-network
    restart: unless-stopped

  # Next.js Frontend
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: powerflow-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - api
    networks:
      - powerflow-network
    restart: unless-stopped

networks:
  powerflow-network:
    driver: bridge