version: '3.8'

services:
  # NestJS API Gateway (Development)
  api:
    image: node:20-alpine
    container_name: powerflow-api-dev
    working_dir: /app
    ports:
      - "4000:4000"
    volumes:
      - ./apps/api:/app
      - api_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev"
    networks:
      - powerflow-network
    restart: unless-stopped

  # Next.js Frontend (Development)
  web:
    image: node:20-alpine
    container_name: powerflow-web-dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
      - web_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev"
    depends_on:
      - api
    networks:
      - powerflow-network
    restart: unless-stopped

networks:
  powerflow-network:
    driver: bridge

volumes:
  api_node_modules:
  web_node_modules: